// * ADMIN USERMANAGEMENT CONSTANTS 
export const ADMIN_LOGIN_REQUEST = 'ADMIN_LOGIN_REQUEST';
export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS';
export const ADMIN_LOGIN_FAIL = 'ADMIN_LOGIN_FAIL';

export const ADMIN_USERLIST_REQUEST = 'ADMIN_USERLIST_REQUEST';
export const ADMIN_USERLIST_SUCCESS = 'ADMIN_USERLIST_SUCCESS';
export const ADMIN_USERLIST_FAIL = 'ADMIN_USERLIST_FAIL';

export const ADMIN_DELETEUSER_REQUEST = 'ADMIN_DELETEUSER_REQUEST';
export const ADMIN_DELETEUSER_SUCCESS = 'ADMIN_DELETEUSER_SUCCESS';
export const ADMIN_DELETEUSER_FAIL = 'ADMIN_DELETEUSER_FAIL';

export const ADMIN_USERDETAILS_REQUEST = 'ADMIN_USERDETAILS_REQUEST';
export const ADMIN_USERDETAILS_SUCCESS = 'ADMIN_USERDETAILS_SUCCESS';
export const ADMIN_USERDETAILS_FAIL = 'ADMIN_USERDETAILS_FAIL';  
export const ADMIN_USERDETAILS_RESET = 'ADMIN_USERDETAILS_RESET';

export const ADMIN_UPDATEUSER_REQUEST = 'ADMIN_UPDATEUSER_REQUEST';
export const ADMIN_UPDATEUSER_SUCCESS = 'ADMIN_UPDATEUSER_SUCCESS';
export const ADMIN_UPDATEUSER_FAIL = 'ADMIN_UPDATEUSER_FAIL';
export const ADMIN_UPDATEUSER_RESET = 'ADMIN_UPDATEUSER_RESET';

export const ADMIN_CREATEUSER_REQUEST = 'ADMIN_CREATEUSER_REQUEST';
export const ADMIN_CREATEUSER_SUCCESS = 'ADMIN_CREATEUSER_SUCCESS';
export const ADMIN_CREATEUSER_FAIL = 'ADMIN_CREATEUSER_FAIL';
export const ADMIN_CREATEUSER_RESET = 'ADMIN_CREATEUSER_RESET';

// * ADMIN PRODUCTMANGEMENT CONSTANTS 

export const ADMIN_PRODUCTLIST_REQUEST = 'ADMIN_PRODUCTLIST_REQUEST';
export const ADMIN_PRODUCTLIST_SUCCESS = 'ADMIN_PRODUCTLIST_SUCCESS';
export const ADMIN_PRODUCTLIST_FAIL = 'ADMIN_PRODUCTLIST_FAIL';

export const ADMIN_DELETEPRODUCT_REQUEST = 'ADMIN_DELETEPRODUCT_REQUEST';
export const ADMIN_DELETEPRODUCT_SUCCESS = 'ADMIN_DELETEPRODUCT_SUCCESS';
export const ADMIN_DELETEPRODUCT_FAIL = 'ADMIN_DELETEPRODUCT_FAIL'; 

export const ADMIN_ADDPRODUCT_REQUEST = 'ADMIN_ADDPRODUCT_REQUEST';
export const ADMIN_ADDPRODUCT_SUCCESS = 'ADMIN_ADDPRODUCT_SUCCESS';
export const ADMIN_ADDPRODUCT_FAIL = 'ADMIN_ADDPRODUCT_FAIL';
export const ADMIN_ADDPRODUCT_RESET = 'ADMIN_ADDPRODUCT_RESET';