export const ADMIN_LOGIN_REQUEST = 'ADMIN_LOGIN_REQUEST';
export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS';
export const ADMIN_LOGIN_FAIL = 'ADMIN_LOGIN_FAIL';

export const ADMIN_USERLIST_REQUEST = 'ADMIN_USERLIST_REQUEST';
export const ADMIN_USERLIST_SUCCESS = 'ADMIN_USERLIST_SUCCESS';
export const ADMIN_USERLIST_FAIL = 'ADMIN_USERLIST_FAIL';

export const ADMIN_DELETEUSER_REQUEST = 'ADMIN_DELETEUSER_REQUEST';
export const ADMIN_DELETEUSER_SUCCESS = 'ADMIN_DELETEUSER_SUCCESS';
export const ADMIN_DELETEUSER_FAIL = 'ADMIN_DELETEUSER_FAIL';
